### PR TITLE
Fixed compilation with qt5.5

### PR DESCRIPTION
**Pull request by JoonasMelin**
This adds the necessary libraries for compiling the GCS with qt5.5.
I did not test with the previous QT version so it might cause issues there.

### CODE REVIEW

**Comment by parched** [comment]
Hi Joonas,

The OpenPilot developers have split into two forks, OPNG and [LibrePilot](https://github.com/librepilot/LibrePilot). OPNG has dropped the GCS and LibrePilot already has these changes, so unfortunately these may never be merged. May I ask what distro you are using?

**Comment by JoonasMelin** [comment]
Ah - this explains a lot. I am running Arch so I could also propose some modifications to the AUR packages to point to right sources.

**Comment by parched** [comment]
Ah yes, I was the Arch maintainer for openpilot until the fork. I will be adding LibrePIlot when the first release is done. Now that there is openpilot 15.05.01 source I guess we add it to the AUR with this patch until LibrePilot does it's first release

**Comment by parched** [comment]
Actually it looks like 15.05.01 isn't the proper release archive so I won't be adding it to the AUR.

**Pull request closed without merging**
